# Generated by Django 4.1.7 on 2023-02-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
